# Generated by Django 4.1.1 on 2022-09-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_account_accountstock_accountcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency'),
        ),
    ]
