# Generated by Django 4.1.1 on 2022-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_currency_sign_alter_stock_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='sign',
            field=models.CharField(choices=[('$', 'Dollar'), ('R', 'Ruble'), ('t', 'Junior')], max_length=1),
        ),
    ]
