# Generated by Django 4.1.1 on 2022-09-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_currency_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(blank=True, choices=[('$', 'Dollar'), ('R', 'Ruble'), ('t', 'Junior')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency'),
        ),
    ]
